language: cpp
compiler: clang

before_script:
  - git submodule update --init --recursive
  - mkdir -p build && cd build && cmake ..

script:
  - cd build && make
  - cd build && ctest --output-on-failure